### ISSUE TITLE
Contribution?

### ISSUE THREAD

**Issue by SherifRefaat** [samcragg/Crest#1]
Hi, @samcragg, 

I wanted to tell you how much I appreciate your project here. I am sorry for writing to you here in the issues.
I can't seem to find any helpful documentation on the project here so I can contribute.
I'd be happy to help.

Thanks.

**Comment by SherifRefaat** [comment]
Great. I am still reading the code base because I need to understand a lot about this. Because I think reading the source code helps me understand what this project is and what is not. Because I have got a lot of ideas.

Here are some questions:
- What did you mean by JWT?
- Are you planing for this to be a standard?

**Comment by samcragg** [comment]
JWTs are a way to do claims based security - see https://jwt.io/ for some examples. Including it in the framework will allow for tokens to be made available for user code to use and also the decorating of methods as being marked as secure or allowing anonymous access. These tokens could come from OpenID providers, as it's a common standard.

Regarding a standard the library will follow, I don't think there exists a REST standard, but would like to follow the principles of http://www.restapitutorial.com/

**Comment by SherifRefaat** [comment]
If you want, we can start by creating a case and assigning it to me. It could be any task.

**Comment by samcragg** [comment]
I've added some issues now, a good first one would be to upgrade the anaylzer project. If you do decide to take any of them add a comment.

I'm just in the process of updating the documentation at the moment which should hopefully help with the issues.

Thanks again for your interest.
