### ISSUE TITLE
When executing PowerShell in PreCompile step of any project, use process scoped ByPass execution policy

### ISSUE THREAD

**Issue by SherifRefaat** [samcragg/Crest#13]
Not all the users have a permissive powershell execution policy set globally.

For example in Crest.Host.csproj

```
   <Target Name="PrecompileScript" BeforeTargets="BeforeBuild">
    <Exec Command="powershell ../../build/exclude_dry_ioc_from_stylecop.ps1" />
  </Target>
```

**Comment by SherifRefaat** [comment]
Working on it.

**Comment by samcragg** [comment]
Thanks for doing that.

I'll setup another issue to investigate moving to [Cake](https://cakebuild.net/), as I'm conscious that PowerShell only works on Windows.
